### ISSUE TITLE
NameError: name 'NonDynamicallyQuantizableLinear' is not defined

### ISSUE THREAD

**Issue by yuanzhiyong1999** [mlvlab/QAT#3]
I am using torch1.8.1+cu111 with "NameError: name 'NonDynamicallyQuantizableLinear' is not defined" error.
What is the reason for this?
![image](https://user-images.githubusercontent.com/94682439/232971055-62efa4ea-45cb-4ca2-aa0f-ded5e8414f4e.png)

**Comment by PJin0** [comment]
Could you try changing your pytorch version to 1.9.0 or 1.10.1?

**Comment by EchoDreamer** [comment]
What version of the timm library do you have installed? Whenever I try to install it, it always changes my torch version to torch 2.2_

**Comment by PJin0** [comment]
I used timm==0.9.11 version.
