### ISSUE TITLE
What does the output Z of the QAT exactly mean?

### ISSUE THREAD

**Issue by WWalter-Lee** [mlvlab/QAT#4]
According to the Equation (9): $Z=FFN(LN(\hat Z))+\hat Z$. The $Z$ shuld be a veactor with the same dim as the $\hat Z$ as well as the $X$. So does $Z$ mean the probability of the fact that input $X$ is a sensible Q-A pair? But how does the vector express the probability?

**Comment by PJin0** [comment]
Thank you for the interest to our paper.

The output of Transformer $Z$ is fed to $\text{MLP}(\cdot)$ to get the probability of Q-A pair.

**Comment by WWalter-Lee** [comment]
Thanks for your reply! By the way, is there a link for the supplement mentioned in the paper?

**Comment by PJin0** [comment]
No, there is no link for the supplement. I'm gonna update our arxiv including the supplment.
