### ISSUE TITLE
a question about the code

### ISSUE THREAD

**Issue by ZiyeLuo** [mlvlab/QAT#6]
hello, I found  that there is a bug in the "model_qat.py",in line241 and line 242,.there is no definition about the edge_index, could you please revise them?
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/50188561/234296844-9e69b59f-7f16-4d66-bc18-8f2d2ec97640.png">

**Comment by PJin0** [comment]
Thank you for your feedback. I'm gonna check them and revise them as soon as possible.

**Comment by PJin0** [comment]
I have just revised it. Please pull your code. If you have any issues on our codes, please feel free to reach out to me:)
