### ISSUE TITLE
can not reproduce the result in paper

### ISSUE THREAD

**Issue by ZiyeLuo** [mlvlab/QAT#7]
Thank you for helping me solve the problem of the last bug. I would like to ask if you can provide the bash file of "run_usmle". I can't run out the results in the paper. Also, Also, what machine did you use in the paper?

**Comment by PJin0** [comment]
In our paper, we use a RTX Titan. I'll provide the bash file of run_usmle. 
To solve the issue, could you provide the log of your experiment?

**Comment by ZiyeLuo** [comment]
[newFT_path.medqa_usmle_2e-5.1e-4.1e-2.1e-1_1024.2048.16__seed1_20230427_005601.log.txt](https://github.com/mlvlab/QAT/files/11343123/newFT_path.medqa_usmle_2e-5.1e-4.1e-2.1e-1_1024.2048.16__seed1_20230427_005601.log.txt)
here is my log file! Thank you so much！

**Comment by PJin0** [comment]
Hi, I'm sorry for the late reply. Could you set your '--encoder_lr' to 6e-5 and 'epoch' to 50, 'lr_scheudle' to 'fixed', and 'fc_dim' to 512, 'transformer_dim' to 256, and 'transformer_ffn_dim' to 512?
