### ISSUE TITLE
some questions about data processing

### ISSUE THREAD

**Issue by ZiyeLuo** [mlvlab/QAT#8]
Hello, I would like to ask how did this 45 come about? As far as I know from the paper, a path should consist of at most 2 relationships and 3 nodes. The length of Relation is 17, the length of node is 4, then the length of path should be 17*2+4*3=46
![Uploading iShot_2023-05-05_15.45.00.png…]()

**Comment by ZiyeLuo** [comment]
in modeling_qat ,line 180,
<img width="999" alt="iShot_2023-05-05_15 45 00" src="https://user-images.githubusercontent.com/50188561/236403980-0866e178-415e-4f18-a618-e2cad1b023e9.png">

**Comment by PJin0** [comment]
For obqa and csqa, we use 18 number of relation types and 3 number of node types. So, the length of the path is 45.
